apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
  namespace: default
data:
  stress-test.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
        vus: 20, // number of virtual users
        duration: '30s', // test duration
    };

    export default function () {
        http.get('http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local');
        sleep(1);
    }