apiVersion: batch/v1
kind: CronJob
metadata:
  name: k6-stress-test-cron
  namespace: default
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: loadimpact/k6
            args: ["run", "/scripts/stress-test.js"]
            volumeMounts:
            - name: k6-script
              mountPath: /scripts
          restartPolicy: Never
          volumes:
          - name: k6-script
            configMap:
              name: k6-script
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
