apiVersion: batch/v1
kind: Job
metadata:
  name: k6-stress-test
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: k6
        image: loadimpact/k6
        args: ["run", "/scripts/stress-test.js"]
        volumeMounts:
        - name: k6-script
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: k6-script
        configMap:
          name: k6-script
  backoffLimit: 4